import Container from "@/components/shared/Container";
import { FaTelegram } from "react-icons/fa6";
import { BiSupport } from "react-icons/bi";
import { FaWhatsapp } from "react-icons/fa";
import { FaInstagram } from "react-icons/fa";
import { FaFacebook } from "react-icons/fa";

const ContactUs = () => {
  return (
    <div className="w-full py-20">
      <Container>
        <div className="md:w-7/12 w-full mx-auto ">
          <div>
            <div className="grid grid-cols-12 gap-3">
              <button className="col-span-6  w-full bg-[#ffffff] py-3 rounded border border-slate-400 text-secondary flex justify-center items-center gap-2">
                <BiSupport className="text-[32px]" />{" "}
                <span>Customer Support</span>
              </button>
              <button className=" col-span-6  w-full bg-[#ffffff] py-3 rounded border border-slate-400 text-secondary   flex justify-center items-center gap-2">
                <FaWhatsapp className="text-[32px]" /> <span>WhatsApp</span>
              </button>
              <button className=" col-span-4  w-full bg-[#ffffff] py-3 rounded border border-slate-400 text-secondary  flex justify-center items-center gap-2">
                <FaInstagram className="text-[32px]" /> <span>Instagram</span>
              </button>
              <button className=" col-span-4  w-full bg-[#ffffff] py-3 rounded border border-slate-400 text-secondary  flex justify-center items-center gap-2">
                <FaTelegram className="text-[32px]" /> <span>Telegram</span>
              </button>
              <button className=" col-span-4  w-full bg-[#ffffff] py-3 rounded border border-slate-400 text-secondary  flex justify-center items-center gap-2">
                <FaFacebook className="text-[32px]" /> <span>Facebook</span>
              </button>
            </div>
            <div></div>
          </div>
          <div className="p-5 border border-slate-400 mt-5 flex items-center gap-3">
            <div className=" w-2/12">
              <h2 className="text-4xl text-secondary">Velki</h2>
            </div>
            <div className="w-10/12 border-l border-secondary ">
              <p className="text-secondary text-[14px] pl-5">
                SKYEXCCHANGE.COM is operated by SKYEXCCHANGE.COM Infotech N.V. a
                limited liability company incorporated under the laws of Curacao
                with company Registration number 152377 with registered office
                at Abraham de Veerstraat 9 , Curacao P.O Box 3421 and is
                licensed and regulated by the Curacao authority as the
                regulatory body responsible holding a (Sub-license with License
                number 365/JAZ Sub-License GLH- OCCHKTW0707072017 granted on
                6.07.2017). Players are requested not to contact any untrusted
                sources for skyexcchange.com accounts as this is an online site
                and they can only register independently without any agents.
                Only deposit through the account details generated by the system
                or provided by our official support team.
              </p>
            </div>
          </div>
          <div className="w-8/12 mx-auto mt-10">
            <p className="text-secondary text-center text-[14px]">
              Our website works best in the newest and last prior version of
              these browsers: Google Chrome. Firefox
            </p>
          </div>
        </div>
      </Container>
    </div>
  );
};

export default ContactUs;
