import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Velki | Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="shortcut icon"
          href="https://i.postimg.cc/vZ7Gp4Xx/velki.png"
          sizes="any"
        />
      </head>
      <body className="bg-[#EEEEEE]">
        <Navbar />
        <div className="">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
