import { Inter } from "next/font/google";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";

export const metadata = {
  title: "Velki | Home",
  description: "Generated by create next app",
};

export default function HomeLayout({ children }) {
  return (
    <>
      {children}
      <Footer />
    </>
  );
}
